### PR TITLE
PHPCS coding standards fixes

### PR DESCRIPTION
**Pull request by paulschreiber**
This PR:
* adds phpcs.xml.dist ruleset
* updates composer modules
* fixes formatting issues flagged (via phpcbf)
* fixes or suppresses most PHPCS warnings and errors

### CODE REVIEW

**Comment by paulschreiber** [comment]
Merged in 4.2.0 and resolved conflicts.

**Comment by paulschreiber** [comment]
@diegoquinteiro

**Comment by koconder** [comment]
@paulschreiber any reason for the filename change https://github.com/Automattic/facebook-instant-articles-wp/pull/991/commits/0475b1b61c81e1a751f80c05abcde97302b20e08 - I'm working on the GTM4WP integration and waiting on a rebase on the GTM4WP plugin before i clean this up, just just wanted to understand the change.

**Comment by paulschreiber** [comment]
@koconder This file's name didn't match the class name. (PHPCS flagged that for me.)

**Comment by koconder** [comment]
@paulschreiber all good, thanks for confirming!

**Comment by koconder** [comment]
Bumping PR

**Comment by GaryJones** [comment]
Thanks all. At this point, we're not going to make coding standards changes, and the recent changes for PHP 8 have created a lot of merge conflicts, but I'm re-pointing the PR in case it's revisited in the future, and closing.

**Pull request closed without merging**
