### PR TITLE
Modify embed filters on the only on Instant Articles feed, not always

### PR DESCRIPTION
**Pull request by kitwestneat**
This PR is to address issue #249

### CODE REVIEW

**Comment by diegoquinteiro** [comment]
This will only handle the RSS integration. What about the API integration (that runs when you save the post)?

**Comment by timjacobi** [comment]
@kitwestneat @diegoquinteiro can we move this forward? The related bug has been reported multiple times.

**Comment by kitwestneat** [comment]
we don't use this plugin anymore, so someone else should lead the charge

**Comment by GaryJones** [comment]
Handled with the solution in #1076.

**Pull request closed without merging**
