### PR TITLE
Update Readme re:non-minimal readership

### PR DESCRIPTION
**Pull request by jerclarke**
Now that it is impossible to use this plugin with a site that has ["minimal readership" on Facebook](https://github.com/Automattic/facebook-instant-articles-wp/issues/925#issuecomment-385243511) it is vital that the plugin warns developers not to set it up unless their site already meets the guidelines. This PR is a first step to warn people that after all their hard work getting their site to validate as IA they will still likely be blocked because of minimal readership.

This PR:

* [x] 
* [ ] 
* [ ] 

Follows #

Relates to #925 

Fixes #

### CODE REVIEW

**Comment by jerclarke** [comment]
Any response to the obvious need that this addresses? Did you somehow explain this elsewhere?

**Comment by GaryJones** [comment]
There was a merge conflict, but if you want to fix that up, then I'm happy to take another look :-)

**Comment by jerclarke** [comment]
The PR wasn't really the point, as much as the abject failure of the plugin to warn people that it is useless if your FB page doesn't meet the minimum readership requirements for IA. 

Originally there was no minimum readership requirement, and all the docs, like this one, don't mention it at all:

https://developers.facebook.com/docs/instant-articles/wordpress-quickstart/

But this is disastrous, because for people with a non-qualifying page it can take many many hours of integration to get to the step where you will discover it was all wasted. 

The plugin page should express these limitations and how to check if you qualify BEFORE installing the plugin.

Last time I checked this was still a non-transparent process and there really was no way to check in advance if you qualify. This should be a major warning on the plugin description.

**Comment by GaryJones** [comment]
Looking at https://github.com/Automattic/fb-instant-articles#access-to-instant-articles (this is the bit that has the merge conflict) then it seems that it's already been made more explicit what the requirements are for Instant Articles to be accessed?

**Comment by jerclarke** [comment]
It's not clear. There's no indication of what will happen if your site is deemed to have minimal readership, and it's extremely important because at that point people will have wasted all of their effort leading up to that discovery. 

It's a core failure of IA, not part of this plugin, but there should be warnings in this plugin about it. 

IA is so dead that it hardly matters, no one new is actually trying to set it up. 

But I maintain that it's a specific failure of this plugin (and the linked documentation) that there are no warnings, since otherwise the docs for this plugin seem to tell you everything you need to know. 

If you want to know what i'm talking about, try to set up IA on a small website without a ton of traffic and you'll see how much work you do before you discover you can never use IA.

**Pull request closed without merging**
